core/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views
from .forms import LoginForm


app_name = 'core'
urlpatterns = [
    path('',views.index,name='index'),
    path('contact/',views.contact,name='contact'),
    path('signup/',views.signup,name='signup'),
    path('login/',auth_views.LoginView.as_view(template_name='core/login.html',authentication_form=LoginForm),name='login')
]

dashboard/urls.py
from django.urls import path

from . import views

app_name = 'dashboard'

urlpatterns = [
    path('',views.index,name='Dashboard'),
]

groceSasta/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from core.views import index, contact

urlpatterns = [
    path('',include('core.urls')),
    path('items/',include('items.urls')),
    path('dashboard/',include('dashboard.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

items/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from . import views

app_name = 'items'
urlpatterns = [
    path('<int:pk>/',views.detail,name='detail'),
    path('new/',views.new,name='NewItem'),
]

core/models.py
from django.db import models

# Create your models here.

dashboard/models.py
from django.db import models

# Create your models here.

items/models.py
from django.db import models
from django.contrib.auth.models import User

class Category(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        verbose_name_plural = "Categories"
        ordering = ('name',)

    def __str__(self):
        return self.name

class item(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField(null = True ,blank = True)
    price = models.FloatField()
    image = models.ImageField(upload_to='items_image')
    created_by = models.ForeignKey(User,on_delete= models.CASCADE,related_name='items')
    category = models.ForeignKey(Category,on_delete= models.CASCADE,related_name='items')
    is_sold = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = "Items"
        ordering = ('name',)

    def __str__(self):
        return self.name

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth.models import User

class LoginForm(AuthenticationForm):
    pass

class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username','email','password1','password2')

items/forms.py
from django import forms

from .models import item

class NewItemForm(forms.ModelForm):
    class Meta:
        model = item
        fields = ('category','name','description','price','image')

core/views.py
from django.shortcuts import render, redirect
from items.models import Category,item
from .forms import SignUpForm
# Create your views here.
def index(request):
    items = item.objects.filter(is_sold=False)[0:6]
    categories = Category.objects.all()
    return render(request, 'core\index.html',{
    'categories' : categories,
    'items' : items,
    })

def contact(request):
    return render(request, 'core\contacts.html')

def signup(request):
    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/login/')
        else:
            print(form.errors)
    else:
        form = SignUpForm()
    return render(request, 'core/signup.html', {
        'form': form
    })

dashboard/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from items.models import item
# Create your views here.

@login_required()
def index(request):
    items = item.objects.filter(created_by=request.user)
    print(items)
    return render(request, 'dashboard/index.html', {'items': items})

items/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import item
from django.contrib.auth.decorators import login_required
from .forms import NewItemForm

def detail(request, pk):
    Item = get_object_or_404(item, pk=pk)
    related_items = item.objects.filter(category=Item.category, is_sold=False).exclude(pk=pk)[0:3]
    return render(request, 'item/detail.html', {
        'item': Item,
        'related': related_items,
    })
@login_required()
def new(request):
    if (request.method == "POST"):
        form = NewItemForm(request.POST,request.FILES)
        if (form.is_valid()):
            item = form.save(commit=False)
            item.created_by = request.user
            item.save()
            return redirect('items:detail',pk=item.id)
    form = NewItemForm()

    return render(request, 'item/form.html',{
        'form': form
    })

core/templates/core/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block Title %} {% endblock %} | GroceSasta</title>
    <script src="http://cdn.tailwindcss.com"></script>
</head>
<body>
<nav class="bg-gray-800">
  <div class="max-w-7xl mx-auto px-3 sm:px-6 lg:px-8">
    <div class="flex items-center justify-between h-16">
      <div class="flex items-center">
        <span class="text-white font-bold text-lg">GroceSasta</span>
      </div>
      <div class="flex items-center">
          {% if request.user.is_authenticated %}
              <a href="{% url 'items:NewItem' %}" class="text-gray-300 hover:text-white m-4">New Item</a>
            <a href="#" class="text-gray-300 hover:text-white">Inbox</a>
            <a href="{% url 'dashboard:Dashboard' %}" class="ml-4 bg-gray-700 text-white py-2 px-4 rounded hover:bg-gray-500">Dashboard</a>

          {% else %}
              <a href="{% url 'items:NewItem' %}" class="text-gray-300 hover:text-white m-4">New Item</a>
            <a href="{% url 'core:login' %}" class="text-gray-300 hover:text-white">Sign In</a>
            <a href="{% url 'core:signup' %}" class="ml-4 bg-gray-700 text-white py-2 px-4 rounded hover:bg-gray-500">Sign Up</a>
          {% endif %}
      </div>
    </div>
  </div>
</nav>
<div class="px-16 py-3">
{% block content %}
{% endblock %}
</div>
</body>
<footer class="bg-gray-800">
  <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
    <div class="flex flex-wrap justify-between">
      <div class="w-full lg:w-auto mb-8 lg:mb-0">
        <span class="text-gray-400">&copy; 2023 GroceSasta. All rights reserved.</span>
      </div>
      <div class="w-full lg:w-auto">
        <ul class="flex flex-wrap justify-center lg:justify-end">
          <li>
            <a href="#" class="text-gray-400 hover:text-white px-3 py-2">About</a>
          </li>
          <li>
            <a href="#" class="text-gray-400 hover:text-white px-3 py-2">Privacy Policy</a>
          </li>
          <li>
            <a href="{% url 'core:contact' %}" class="text-gray-400 hover:text-white px-3 py-2">Contact</a>
          </li>
            <li>
            <a href="#" class="text-gray-400 hover:text-white px-3 py-2">Terms of Service</a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</footer>
</html>

core/templates/core/contacts.html
{% extends 'core/base.html' %}
{% block Title %}Contact{% endblock %}

{% block content %}
<h1 class="text-lg">Contact GroceSasta through Social Media!</h1>
{% endblock %}

core/templates/core/index.html
{% extends 'core/base.html' %}
{% block Title %}Welcome{% endblock %}

{% block content %}
<div  class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
  {% for item in items %}
    <a href="{% url 'items:detail' item.id %}" class="bg-white shadow-md rounded-lg overflow-hidden">
      <img class="w-full h-64 object-cover" src="{{ item.image.url }}" alt="{{ item.name }}">
      <div class="p-4">
        <h3 class="font-semibold text-gray-700">{{ item.name }}</h3>
        <p class="text-gray-500">${{ item.price }}</p>
        <p class="text-gray-600">{{ item.description }}</p>
      </div>
    </a>
  {% endfor %}
</div>
{% endblock %}

core/templates/core/login.html
{% extends 'core/base.html' %}
{% block Title %}SignIn{% endblock %}
{% block content %}
  <div class="flex items-center justify-center py-12 px-4 sm:px-6 lg:px-8">
    <div class="max-w-md w-full space-y-8 bg-gray-200 rounded-lg shadow-lg mx-auto p-3">
      <div>
        <h2 class="mt-6 text-center text-3xl font-extrabold text-gray-900">
          Log In
        </h2>
      </div>
      <form class="w-full max-w-lg" method="POST">
        {% csrf_token %}
        {% for field in form %}
          <div class="mb-4">
            {{ field.label_tag }}
            {{ field }}
            {% if field.help_text %}
              <small class="text-gray-600">{{ field.help_text }}</small>
            {% endif %}
            {% for error in field.errors %}
              <p class="text-red-500 text-sm mt-1">{{ error }}</p>
            {% endfor %}
          </div>
        {% endfor %}
        <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" type="submit">Sign in</button>
      </form>
    </div>
  </div>
{% endblock %}

core/templates/core/signup.html
{% extends 'core/base.html' %}
{% block Title %}SignUp{% endblock %}
{% block content %}
  <div class="flex items-center justify-center py-12 px-4 sm:px-6 lg:px-8">
    <div class="max-w-md w-full space-y-8 bg-gray-200 rounded-lg shadow-lg mx-auto p-3">
      <div>
        <h2 class="mt-6 text-center text-3xl font-extrabold text-gray-900">
          Sign up for an account
        </h2>
      </div>
      <form class="w-full max-w-lg" method="POST">
        {% csrf_token %}
        {% for field in form %}
          <div class="mb-4">
            {{ field.label_tag }}
            {{ field }}
            {% if field.help_text %}
              <small class="text-gray-600">{{ field.help_text }}</small>
            {% endif %}
            {% for error in field.errors %}
              <p class="text-red-500 text-sm mt-1">{{ error }}</p>
            {% endfor %}
          </div>
        {% endfor %}
        <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" type="submit">Sign up</button>
      </form>
    </div>
  </div>
{% endblock %}

dashboard/templates/dashboard/index.html
{% extends 'core/base.html' %}
{% block Title %}Dashboard{% endblock %}

{% block content %}
    <h1 class="font-semibold mx-auto text-3xl text-center">My Items</h1>
<div  class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
  {% for item in items %}
    <a href="{% url 'items:detail' item.id %}" class="bg-white shadow-md rounded-lg overflow-hidden">
      <img class="w-full h-64 object-cover" src="{{ item.image.url }}" alt="{{ item.name }}">
      <div class="p-4">
        <h3 class="font-semibold text-gray-700">{{ item.name }}</h3>
        <p class="text-gray-500">${{ item.price }}</p>
        <p class="text-gray-600">{{ item.description }}</p>
      </div>
    </a>
  {% endfor %}
</div>
{% endblock %}

items/templates/item/detail.html
{% extends 'core/base.html' %}
{% block Title %}{{ item.name }}{% endblock %}

{% block content %}
<div class="flex flex-col items-center md:flex-row items-start justify-start">
  <div class="shadow-lg py-3 w-full md:w-1/2">
    <img class="w-full h-full object-cover" src="{{ item.image.url }}" alt="{{ item.name }}">
  </div>
  <div class="bg-gray-200 mx-10 py-3 w-full md:w-1/2 p-8">
    <h1 class="py-3 text-2xl font-semibold text-gray-800"><b>{{ item.name }}</b></h1>
    <p class="py-3 text-gray-500"><b>Price: </b>PKR{{ item.price }}</p>
    <p class="py-3 text-gray-600"><b>Description: </b>{{ item.description }}</p>
      <p class="py-3 text-gray-600"><b>Seller: </b>{{ item.created_by }}</p>
      <button class="p-3 rounded-lg hover:bg-gray-800 bg-gray-500 text-white">Contact Seller</button>
  </div>
</div>
    {% if related %}
    <div class="mt-20 mx-10"><p class="font-semibold text-3xl">Related Items:</p>
        <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {% for item in related %}
                <a href="{% url 'items:detail' item.id %}" class="bg-white shadow-md rounded-lg overflow-hidden">
                    <img class="w-full h-64 object-cover" src="{{ item.image.url }}" alt="{{ item.name }}">
                    <div class="p-4">
                        <h3 class="font-semibold text-gray-700">{{ item.name }}</h3>
                        <p class="text-gray-500">${{ item.price }}</p>
                        <p class="text-gray-600">{{ item.description }}</p>
                    </div>
                </a>
            {% endfor %}
        </div>
    {% endif %}
    </div>
{% endblock %}

items/templates/item/form.html
{% extends 'core/base.html' %}
{% block Title %}Create New Item{% endblock %}
{% block content %}
  <h1 class="mx-auto font-semibold text-2xl">Create New Item</h1>
  <form method="post" action="." enctype="multipart/form-data" class="w-3/6 p-10 mx-auto items-center rounded-lg shadow-lg bg-gray-300">
    {% csrf_token %}
      <div>
      <label for="{{ form.category.id_for_label }}">Category:</label><br>
      {{ form.category }}
    </div>
    <div>
      <label for="{{ form.name.id_for_label }}">Name:</label><br>
      {{ form.name }}
    </div>
    <div>
      <label for="{{ form.description.id_for_label }}">Description:</label><br>
      {{ form.description }}
    </div>
    <div>
      <label for="{{ form.price.id_for_label }}">Price:</label><br>
      {{ form.price }}
    </div>
      <div>
      <label for="{{ form.image.id_for_label }}">Image:</label><br>
      {{ form.image }}
    </div>
    <button class="bg-gray-500 hover:bg-gray-800 rounded-sm my-3 p-3" type="submit">Create</button>
  {% for error in field.errors %}
              <p class="text-red-500 text-sm mt-1">{{ error }}</p>
            {% endfor %}
  </form>
{% endblock %}